---
name: Module scan

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

permissions: read-all

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Add the super-linter env file to the GITHUB_ENV
      - run: cat .github/super-linter.env >> "$GITHUB_ENV"

      # Scan with GH Super-Linter slim
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main

      # Scan with Checkov
      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@master
        with:
          quiet: true
          output_format: github_failed_only

      # Scan with Trivy
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          severity: "CRITICAL,HIGH,MEDIUM"
          scanners: "vuln,config,secret"
