---
name: Terraform Tests

on:
  push:
    branches-ignore:
      - "main"

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Test
        run: terraform test
        env:
          TF_VAR_client_id: ${{ secrets.PORT_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.PORT_CLIENT_SECRET }}
